# Generated by Django 5.1.5 on 2025-01-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='height',
            field=models.FloatField(default=0.0),
        ),
    ]
